#name: superlinter
on:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    #strategy:
      #fail-fast: false
      #matrix:
        #flag: [ONLY_ARMV7, ONLY_ARM64, UNIVERSAL]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
          local-cache: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4
      - run: |
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.9.0
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.5.0
          haxelib install flixel-addons 2.9.0
          haxelib install newgrounds 1.3.0
          haxelib install hscript 2.5.0
          haxelib git faxe https://github.com/ashea-code/faxe
          haxelib install polymod 1.7.0
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
         #haxelib install hxcpp-debug-server 1.2.4
      - run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - run: haxelib run lime build android
      - uses: actions/upload-artifact@v4
        with:
          name: VsWhitty
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: error
